language: python

cache:
  - pip

python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7-dev"

env:
 - DJANGO_VERSION=1.11.* DATABASE_SETTINGS='settings_postgresql.py'
 - DJANGO_VERSION=2.0.* DATABASE_SETTINGS='settings_postgresql.py'
 - DJANGO_VERSION=2.1.* DATABASE_SETTINGS='settings_postgresql.py'

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_VERSION=2.0.* DATABASE_SETTINGS='settings_postgresql.py'
  - python: "2.7"
    env: DJANGO_VERSION=2.1.* DATABASE_SETTINGS='settings_postgresql.py'
  - python: "3.7-dev"
    env: DJANGO_VERSION=1.11.* DATABASE_SETTINGS='settings_postgresql.py'

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
  - psql -c 'create database calaccess_scraped;' -U postgres
  - cp example/project/$DATABASE_SETTINGS.template example/project/settings_local.py

script:
 - flake8 calaccess_scraped
 - coverage run example/manage.py test calaccess_scraped

after_success:
 - coveralls
