language: python

cache:
  - pip

python:
 - "3.5"
 - "3.6"
 - "3.7-dev"

addons:
 postgresql: "9.6"

env:
 - DJANGO_VERSION=1.11.*
 - DJANGO_VERSION=2.0.*
 - DJANGO_VERSION=2.1.*

matrix:
  exclude:
  - python: "3.7-dev"
    env: DJANGO_VERSION=1.11.*

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
  - psql -c 'create database calaccess_scraped;' -U postgres
  - cp example/project/settings_postgresql.py.template example/project/settings_local.py

script:
 - flake8 calaccess_scraped
 - coverage run example/manage.py test calaccess_scraped

after_success:
 - coveralls
