language: python

cache:
  - pip

python:
 - "2.7"
 - "3.5"
 - "3.6"

env:
 - DJANGO_VERSION=1.10
 - DJANGO_VERSION=1.11

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

script:
 - flake8 calaccess_scraped
 - coverage run example/manage.py test calaccess_scraped

after_success:
 - coveralls
